-- Generated by tools/new_script.py
-- Preferred authoring model: function-style hook with ctx.
-- Keep directive/return-table only for fallback tests and bring-up.

function __HOOK_NAME__(ctx)
  local session_id = ctx and ctx.session_id or nil

  if session_id and "__NOTICE__" ~= "TODO: optional notice" then
    server.send_notice(session_id, "__NOTICE__")
  end

  -- Example deny/block return:
  -- return { decision = "__DECISION__", reason = "__REASON__" }
  return { decision = "__DECISION__" }
end
