{
 "title": "Load Balancer",
 "tags": [
  "haproxy",
  "load-balancer"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "HAProxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HAProxy Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"haproxy\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Frontend Current Sessions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_frontend_current_sessions{proxy=\"fe_gateway\"}",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Frontend Sessions (/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops/s" } },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_sessions_total{proxy=\"fe_gateway\"}[1m])",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Backend Current Sessions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_backend_current_sessions{proxy=\"be_gateway\"}",
     "legendFormat": "{{proxy}}"
    }
   ]
  }
 ]
}